### ISSUE TITLE
你好不支持直接在md中写代码吗

### ISSUE THREAD

**Issue by seepine** [cjSound/vuepress-plugin-demo-container-vue3#2]
我md如下内容，报错
```markdown
# Hello VuePress


## test

::: demo 爱上佛龛送饭送
<template>
    <div>testttttttttttt</div>
</template>
:::

```

没有渲染出来
![image](https://user-images.githubusercontent.com/93666053/151692755-8493ddff-0837-44ff-9cd3-6a6360bd054e.png)

**Comment by cjSound** [comment]
你好，不支持直接在md中直接写代码的形式哦
直接在md中写组件的路径就可以了

```md
::: demo 引用Antd组件
test/test1
:::
```
- 具体可以看下[文档哦](https://www.cjsound.cn/vuepress2-plugin/guide/demo.html)

**Comment by seepine** [comment]
好的多谢

**Comment by justforuse** [comment]
> 你好，不支持直接在md中直接写代码的形式哦 直接在md中写组件的路径就可以了
> 
> ```lisp
> ::: demo 引用Antd组件
> test/test1
> :::
> ```
> 
> * 具体可以看下[文档哦](https://www.cjsound.cn/vuepress2-plugin/guide/demo.html)

@cjSound  你好，请问不支持内部写代码，是有什么技术限制吗，fs.readFileSync和直接使用内部的内容有什么区别吗

**Comment by cjSound** [comment]
@justforuse 你好
整个插件其实就两件事情
- 1、读取示例代码
- 2、示例代码转为html

回到问题 **fs.readFileSync和直接使用内部的内容有什么区别吗**，介绍下两种思路

- 当前插件工作模式
    - 提前批量注册了componentsDir下面的所有组件，
    - 通过 md扩展，获取到组件路径以及 组件注册的Key ```fs.readFileSync是通过path获取源代码示例```
    - 传入源代码 以及组件Key
    - 利用vue **component**渲染组件 实现上述第二步效果，展示示例代码等

- md内部编写示例，大致步骤
    - md扩展，获取示例源代码
    - 将源代码，要利用vue3的模板编译 compiler 解析，并注册成当前页面的子组件，但是这一块目前还没有过多研究
    - 后续也是一样的 传入源代码和注册的组件Key
